"""
Lakebase-Powered AI Support App
A support ticket system that stores operational data in Lakebase (Databricks-managed Postgres).

Features:
- Create and manage support tickets
- Add messages to tickets
- Update ticket status
- View all tickets and their message history

Run locally:
    python app.py
Deploy as a Databricks App using app.yaml.
"""

import logging
import os
import uuid
from datetime import datetime

from databricks.sdk import WorkspaceClient
from flask import Flask, jsonify, render_template, request

import lakebase

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("support-app")

app = Flask(__name__)
_w = WorkspaceClient()

TICKETS_TABLE = os.environ.get("TICKETS_TABLE", "tickets")
MESSAGES_TABLE = os.environ.get("MESSAGES_TABLE", "ticket_messages")


def _current_user_email() -> str:
    """
    Resolve the current user's email.
    Databricks Apps inject the logged-in user's identity via the
    X-Forwarded-Email header on every request. Fall back to the Databricks
    SDK's current_user API for local development.
    """
    header_email = request.headers.get("X-Forwarded-Email")
    if header_email:
        return header_email
    return _w.current_user.me().user_name


def ensure_tables():
    """Create the tickets and ticket_messages tables if they don't exist."""
    
    # Create tickets table with auto-generated 6-char random ID
    lakebase.run_write(
        f"""
        CREATE TABLE IF NOT EXISTS {TICKETS_TABLE} (
            ticket_id TEXT PRIMARY KEY DEFAULT substring(md5(random()::text || clock_timestamp()::text), 1, 6),
            title TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            priority TEXT NOT NULL DEFAULT 'medium',
            category TEXT NOT NULL DEFAULT 'general',
            created_by TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    
    # Add priority and category columns if they don't exist (for existing tables)
    try:
        lakebase.run_write(
            f"ALTER TABLE {TICKETS_TABLE} ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'medium'"
        )
        lakebase.run_write(
            f"ALTER TABLE {TICKETS_TABLE} ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'general'"
        )
    except Exception as e:
        logger.info(f"Columns may already exist: {e}")
    
    # Create ticket_messages table with auto-generated 6-char random ID
    lakebase.run_write(
        f"""
        CREATE TABLE IF NOT EXISTS {MESSAGES_TABLE} (
            message_id TEXT PRIMARY KEY DEFAULT substring(md5(random()::text || clock_timestamp()::text), 1, 6),
            ticket_id TEXT NOT NULL REFERENCES {TICKETS_TABLE}(ticket_id) ON DELETE CASCADE,
            message_text TEXT NOT NULL,
            author TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    
    # Create index for faster ticket message lookups
    lakebase.run_write(
        f"""
        CREATE INDEX IF NOT EXISTS idx_{MESSAGES_TABLE}_ticket_id
        ON {MESSAGES_TABLE} (ticket_id, created_at DESC)
        """
    )


def initialize_sample_data():
    """Add sample data if the database is empty."""
    # Check if we already have data
    existing = lakebase.run_query(f"SELECT COUNT(*) as count FROM {TICKETS_TABLE}")
    if existing[0]['count'] > 0:
        logger.info("Sample data already exists, skipping initialization")
        return
    
    logger.info("Initializing sample data...")
    
    # Sample tickets - IDs will be auto-generated by database
    tickets = [
        ("Cannot access workspace", "open", "user1@databricks.com"),
        ("Cluster fails to start", "in_progress", "user2@databricks.com"),
        ("Need help with SQL query", "resolved", "user3@databricks.com"),
    ]
    
    ticket_ids = []
    for title, status, created_by in tickets:
        result = lakebase.run_write_returning(
            f"INSERT INTO {TICKETS_TABLE} (title, status, created_by) VALUES (%s, %s, %s) RETURNING ticket_id",
            (title, status, created_by)
        )
        ticket_ids.append(result[0]['ticket_id'])
    
    # Sample messages for each ticket
    messages = [
        # Ticket 1 messages
        (str(uuid.uuid4()), ticket_ids[0], "I'm getting a 403 error when trying to access my workspace.", "user1@databricks.com"),
        (str(uuid.uuid4()), ticket_ids[0], "Can you please check my permissions?", "user1@databricks.com"),
        
        # Ticket 2 messages
        (str(uuid.uuid4()), ticket_ids[1], "My cluster is stuck in 'Pending' state for 10 minutes.", "user2@databricks.com"),
        (str(uuid.uuid4()), ticket_ids[1], "I'm looking into this - checking your cloud resource limits.", "support@databricks.com"),
        (str(uuid.uuid4()), ticket_ids[1], "Found the issue - you've reached your instance quota. Requesting an increase.", "support@databricks.com"),
        
        # Ticket 3 messages
        (str(uuid.uuid4()), ticket_ids[2], "How do I join two tables using Unity Catalog?", "user3@databricks.com"),
        (str(uuid.uuid4()), ticket_ids[2], "You can use standard SQL JOIN syntax with fully qualified names like catalog.schema.table", "support@databricks.com"),
        (str(uuid.uuid4()), ticket_ids[2], "Thanks! That worked perfectly.", "user3@databricks.com"),
    ]
    
    for message_id, ticket_id, message_text, author in messages:
        lakebase.run_write(
            f"INSERT INTO {MESSAGES_TABLE} (message_id, ticket_id, message_text, author) VALUES (%s, %s, %s, %s)",
            (message_id, ticket_id, message_text, author)
        )
    
    logger.info("Sample data initialized successfully")


@app.route("/healthz")
def healthz():
    return jsonify({"status": "ok"})


@app.errorhandler(Exception)
def handle_exception(err):
    """Ensure all unhandled errors return JSON."""
    logger.exception("Unhandled exception while processing request")
    status_code = getattr(err, "code", 500)
    if not isinstance(status_code, int):
        status_code = 500
    return jsonify({"error": str(err)}), status_code


@app.route("/")
def index():
    """Main UI for the support ticket system."""
    return render_template("index.html")


@app.route("/tickets", methods=["GET"])
def get_tickets():
    """Get all tickets with basic info, with optional status filtering."""
    status_filter = request.args.get('status', '').strip().lower()
    
    query = f"""
        SELECT t.ticket_id, t.title, t.status, t.priority, t.category, t.created_by, t.created_at,
               COUNT(m.message_id) as message_count
        FROM {TICKETS_TABLE} t
        LEFT JOIN {MESSAGES_TABLE} m ON t.ticket_id = m.ticket_id
    """
    
    params = None
    if status_filter:
        query += " WHERE t.status = %s"
        params = (status_filter,)
    
    query += f"""
        GROUP BY t.ticket_id, t.title, t.status, t.priority, t.category, t.created_by, t.created_at
        ORDER BY t.created_at DESC
    """
    
    tickets = lakebase.run_query(query, params) if params else lakebase.run_query(query)
    return jsonify(tickets)


@app.route("/tickets/<ticket_id>", methods=["GET"])
def get_ticket(ticket_id):
    """Get a specific ticket with all its messages."""
    # Get ticket details
    tickets = lakebase.run_query(
        f"SELECT * FROM {TICKETS_TABLE} WHERE ticket_id = %s",
        (ticket_id,)
    )
    
    if not tickets:
        return jsonify({"error": "Ticket not found"}), 404
    
    ticket = tickets[0]
    
    # Get messages for this ticket
    messages = lakebase.run_query(
        f"""
        SELECT message_id, message_text, author, created_at
        FROM {MESSAGES_TABLE}
        WHERE ticket_id = %s
        ORDER BY created_at ASC
        """,
        (ticket_id,)
    )
    
    ticket['messages'] = messages
    return jsonify(ticket)


@app.route("/tickets", methods=["POST"])
def create_ticket():
    """Create a new support ticket."""
    if not request.is_json:
        return jsonify({"error": "Request must be JSON"}), 400
    
    title = request.json.get("title", "").strip()
    initial_message = request.json.get("message", "").strip()
    priority = request.json.get("priority", "medium").strip().lower()
    category = request.json.get("category", "general").strip().lower()
    
    if not title:
        return jsonify({"error": "Title is required"}), 400
    
    if not initial_message:
        return jsonify({"error": "Initial message is required"}), 400
    
    valid_priorities = ["low", "medium", "high", "critical"]
    if priority not in valid_priorities:
        return jsonify({"error": f"Priority must be one of: {', '.join(valid_priorities)}"}), 400
    
    valid_categories = ["general", "access", "cluster", "support", "billing", "other"]
    if category not in valid_categories:
        return jsonify({"error": f"Category must be one of: {', '.join(valid_categories)}"}), 400
    
    author = _current_user_email()
    
    # Create the ticket
    ticket_result = lakebase.run_write_returning(
        f"""
        INSERT INTO {TICKETS_TABLE} (title, status, priority, category, created_by)
        VALUES (%s, 'open', %s, %s, %s)
        RETURNING ticket_id, title, status, priority, category, created_by, created_at
        """,
        (title, priority, category, author)
    )
    
    if not ticket_result:
        return jsonify({"error": "Failed to create ticket"}), 500
    
    ticket = ticket_result[0]
    ticket_id = ticket['ticket_id']
    
    # Add the initial message
    lakebase.run_write(
        f"INSERT INTO {MESSAGES_TABLE} (ticket_id, message_text, author) VALUES (%s, %s, %s)",
        (ticket_id, initial_message, author)
    )
    
    return jsonify(ticket), 201


@app.route("/tickets/<ticket_id>/messages", methods=["POST"])
def add_message(ticket_id):
    """Add a message to an existing ticket."""
    if not request.is_json:
        return jsonify({"error": "Request must be JSON"}), 400
    
    message_text = request.json.get("message", "").strip()
    
    if not message_text:
        return jsonify({"error": "Message text is required"}), 400
    
    # Verify ticket exists
    tickets = lakebase.run_query(
        f"SELECT ticket_id FROM {TICKETS_TABLE} WHERE ticket_id = %s",
        (ticket_id,)
    )
    
    if not tickets:
        return jsonify({"error": "Ticket not found"}), 404
    
    author = _current_user_email()
    message_id = str(uuid.uuid4())
    
    # Insert the message
    message_result = lakebase.run_write_returning(
        f"""
        INSERT INTO {MESSAGES_TABLE} (message_id, ticket_id, message_text, author)
        VALUES (%s, %s, %s, %s)
        RETURNING message_id, ticket_id, message_text, author, created_at
        """,
        (message_id, ticket_id, message_text, author)
    )
    
    if not message_result:
        return jsonify({"error": "Failed to add message"}), 500
    
    return jsonify(message_result[0]), 201


@app.route("/tickets/<ticket_id>/status", methods=["PUT"])
def update_status(ticket_id):
    """Update the status of a ticket."""
    if not request.is_json:
        return jsonify({"error": "Request must be JSON"}), 400
    
    new_status = request.json.get("status", "").strip().lower()
    
    valid_statuses = ["open", "in_progress", "resolved", "closed"]
    if new_status not in valid_statuses:
        return jsonify({"error": f"Status must be one of: {', '.join(valid_statuses)}"}), 400
    
    # Update the status
    result = lakebase.run_write_returning(
        f"""
        UPDATE {TICKETS_TABLE}
        SET status = %s
        WHERE ticket_id = %s
        RETURNING ticket_id, title, status, created_by, created_at
        """,
        (new_status, ticket_id)
    )
    
    if not result:
        return jsonify({"error": "Ticket not found"}), 404
    
    return jsonify(result[0])


if __name__ == "__main__":
    # Initialize database on startup
    logger.info("Starting Support App...")
    ensure_tables()
    initialize_sample_data()
    logger.info("Database initialized")
    
    port = int(os.environ.get("PORT", 8000))
    app.run(host="0.0.0.0", port=port, debug=False)